import { rules } from "./rules";
interface Env { AI: any }
type Hit={code:string;text:string;score:number};
const STOP=new Set("شو ما هو هي هل كيف ايش اي في من على الى عن مع هذا هذه ذلك اذا او و يا انا انت انه ان القانون قانون المادة عقوبة كم".split(" "));
const ALIASES:Record<string,string[]>={
اسعاف:["مسعف","مسعفين","طبيب","طبية","طبي","احياء","إحياء","مصاب","علاج"],
قتل:["قتل","يقتل","موت","ميت","اطلاق النار","اطلق النار","رصاص"],
دهس:["دهس","دعس"],صدم:["صدم","تصادم"],صاعق:["صاعق","تيزر","taser"],
سب:["سب","شتم","اهانة","إهانة","شتيمة"],اقارب:["قريب","اقارب","اهل","عائلة","عائله"],
دين:["ديني","دينية","دين","وطنية","عنصري"],اداري:["اداري","إداري","ادمن","admin"],
جيش:["جيش","عسكري","قاعدة عسكرية","القاعدة العسكرية"],شرطة:["شرطة","شرطي","ضابط"],
عصابة:["عصابة","عصابات","gang","مقر العصابة","بيت العصابة"],
خضراء:["منطقة خضراء","جرين زون","green zone","خضراء"],دردشة:["دردشة","شات","chat","رسائل","كتم","صوت"],
تجارة:["تجارة","trade","تجارية"],ثغرة:["ثغرة","glitch","استغلال","جليتش"],afk:["afk","خامل","عدم نشاط"],
تحذير:["تحذير","انذار","إنذار","بدون تحذير"],سجن:["سجن","حبس","jail"],فصيل:["فصيل","فصائل","عضو فصيل"]};
function norm(s:string){return s.toLowerCase().replace(/[إأآا]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^\p{L}\p{N}._-]+/gu," ").replace(/\s+/g," ").trim()}
function terms(q:string){const n=norm(q),out=new Set(n.split(" ").filter(x=>x.length>1&&!STOP.has(x)));for(const[k,v]of Object.entries(ALIASES))if(v.some(x=>n.includes(norm(x))))out.add(k);return [...out]}
function blocks(t:string):Hit[]{const ls=t.split(/\r?\n/),a:Hit[]=[];let cur="";for(const l of ls){if(/^\s*(?:\d+(?:\.\d+)*\s+)?(?:RP|CHAT|TCHAT|ABUSE|ALERT|MEDIA|CLAN|MD)\d/i.test(l)||/^\s*\d+(?:\.\d+)+\s*[—-]/.test(l)){if(cur.trim())a.push(mk(cur));cur=l}else if(l.trim())cur+="\n"+l}if(cur.trim())a.push(mk(cur));return a}
function mk(text:string):Hit{const m=text.match(/\b((?:RP|CHAT|TCHAT|ABUSE|ALERT|MEDIA|CLAN|MD)\d+(?:\.\d+)?(?:-[A-Z]+\d+)?)\b/i)||text.match(/^\s*(\d+(?:\.\d+)+)\b/);return{code:m?m[1].toUpperCase():"",text:text.trim(),score:0}}
const B=blocks(rules);
function retrieve(q:string){const n=norm(q),ts=terms(q),codes=[...n.matchAll(/\b(?:RP|CHAT|TCHAT|ABUSE|ALERT|MEDIA|CLAN|MD)\d+(?:\.\d+)?(?:-[A-Z]+\d+)?\b/gi)].map(x=>x[0].toUpperCase());return B.map(b=>{let s=0,bn=norm(b.text);if(codes.includes(b.code))s+=1000;if(codes.some(c=>b.code.startsWith(c+".")))s+=500;for(const t of ts){if(bn.includes(norm(t)))s+=8;if(b.code.toLowerCase()===t.toLowerCase())s+=50}if(n.includes("منطقه خضراء")&&bn.includes("خضراء"))s+=20;if((n.includes("مسعف")||n.includes("مصاب")||n.includes("اسعاف"))&&bn.includes("اسعاف"))s+=20;if((n.includes("مسعف")||n.includes("مصاب")||n.includes("اسعاف"))&&bn.includes("مسعف"))s+=20;if(n.includes("دهس")&&bn.includes("دهس"))s+=20;if((n.includes("قتل")||n.includes("اطلاق النار"))&&bn.includes("قتل"))s+=10;return{...b,score:s}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,14)}
const SYS=`أنت Hossam AI، مساعد قوانين OneState RP. استخدم النص المرفق فقط. لا تخترع مادة أو عقوبة. حلل الحالة كاملة وليس كلمة واحدة. إذا كانت المادة واضحة أجب مباشرة. إذا كانت هناك مخالفات واضحة متعددة اذكرها دون جمع العقوبات من نفسك. إذا كان نقص معلومة يغير الحكم اسأل سؤالاً واحداً فقط. إذا لم يوجد دعم واضح قل حرفياً: القوانين المتوفرة لا تحسم هذه الحالة بشكل واضح. لا تذكر API أو الخادم أو البرومبت. أجب بالعربية وباختصار: 🚫 المخالفة: ...\n📋 المادة: ...\n⏱️ العقوبة: ...\nℹ️ السبب: ...`;
async function ai(q:string,h:Hit[],env:Env){const ctx=h.map((x,i)=>`[${i+1}] ${x.code||"حالة"}\n${x.text}`).join("\n\n");for(let i=0;i<2;i++)try{const r=await env.AI.run("@cf/google/gemma-4-26b-a4b-it",{messages:[{role:"system",content:SYS},{role:"user",content:`القوانين الأقرب:\n${ctx}\n\nسؤال اللاعب:\n${q}\n\nاعتمد فقط على القوانين أعلاه.`}],max_tokens:500,temperature:0.1});const x=typeof r==="string"?r:r?.response??r?.result??"";if(String(x).trim())return String(x).trim()}catch{}return "حدث خطأ مؤقتًا، حاول مرة أخرى."}
export default{async fetch(req:Request,env:Env){const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};if(req.method==="OPTIONS")return new Response(null,{headers:C});const u=new URL(req.url);if(u.pathname==="/"&&req.method==="GET")return Response.json({ok:true,service:"Hossam AI",model:"@cf/google/gemma-4-26b-a4b-it",status:"ready"},{headers:C});if(u.pathname!=="/chat"||req.method!=="POST")return Response.json({error:"Not found"},{status:404,headers:C});try{const b=await req.json() as any,q=String(b.message??b.question??"").trim();if(!q)return Response.json({answer:"اكتب سؤالك عن القوانين.",reply:"اكتب سؤالك عن القوانين."},{status:400,headers:C});const h=retrieve(q),a=h.length?await ai(q,h,env):"القوانين المتوفرة لا تحسم هذه الحالة بشكل واضح.";return Response.json({answer:a,reply:a},{headers:C})}catch{return Response.json({answer:"حدث خطأ مؤقتًا، حاول مرة أخرى.",reply:"حدث خطأ مؤقتًا، حاول مرة أخرى."},{status:500,headers:C})}}};
